# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ANoV7AhqUPwgpLl_aIF-6euL39uLdxmy
"""

import numpy as np

def unit_vector(v):
    return v / np.linalg.norm(v)
u = np.array([3, -2, 8])
print(unit_vector(u))